- hosts: aliyun
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    mongodb_datadir_prefix: /data
    mongodb_port: 27018

  tasks:
    - name: Create the mongodb user
      user: name=mongodb comment="MongoDB"

    - name: Create the data directory for the namenode metadata
      file: path={{ mongodb_datadir_prefix }} owner=mongodb group=mongodb state=directory

    - name: Install the mongodb package
      apt: name={{ item }} state=present
      with_items:
        - mongodb-server
        - mongodb-clients
        - rsyslog-mongodb

    - name: create data directory for mongodb
      file:
        path: "{{ mongodb_datadir_prefix }}/mongodb-{{ ansible_hostname }}"
        state: directory
        owner: mongodb
        group: mongodb

    - name: create log directory for mongodb
      file: path=/var/log/mongodb state=directory owner=mongodb group=mongodb

    - name: Create the mongodb startup file
      template: src=mongodb.j2 dest=/etc/init.d/mongodb-{{ ansible_hostname }} mode=0655

    - name: Create the mongodb configuration file
      template: src=mongodb.conf.j2 dest=/etc/mongodb-{{ ansible_hostname }}.conf

    # - name: Copy the key file for authentication
    #   copy: src=secret dest={{ mongodb_datadir_prefix }}/secret owner=mongodb group=mongodb mode=0400

    - name: Start the mongodb service
      command: creates=/var/lock/subsys/mongodb-{{ ansible_hostname }} /etc/init.d/mongodb-{{ ansible_hostname }} start
